language: node_js

node_js:
  - '10'

addons:
  chrome: stable

before_install:
  - yarn global add @lhci/cli@0.4.x

branches:
  only:
    - master

cache: yarn

install:
  - yarn install

script:
  - yarn build
  - lhci autorun --rc-overrides.upload.target=temporary-public-storage
  - yarn test
