language: node_js

node_js:
  - '10'

services:
  - docker

branches:
  only:
    - master

cache: yarn

install:
  - yarn install

before_install:
  - docker-compose build

script:
  - docker-compose run --rm test
