version: '3.7'

services:
  dev:
    image: mapping-viz-tools:latest
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint:
      - "yarn"
    command: ["start"]
    ports:
      - "4000:4000"
    volumes:
      - ${PWD}/src:/usr/src/src
  test:
    container_name: mapping-viz-tools-test
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/src:/usr/src/src
    environment:
      - CI=true
    command: yarn test
